#!/bin/bash
# note: /home/cs2/conrada/Catterwampus/bin/ must be in the classpath!

user_path="/home/conrada/"
user_path_labs="/home/cs2/conrada/"

syn_data_path="${user_path_labs}Catterwampus/data/"
real_data_path="${syn_data_path}real/"

config_path="${user_path_labs}Catterwampus/configs/"
output_path="${user_path_labs}Catterwampus/results/"
syn_output_path="${output_path}syn/"
real_output_path="${output_path}real/"

syn_types=( "time-" "matrix-" "seed-" "results-" )
syn_bals=( "r" "c" )
syn_tests=( "s" "m" "l" )
syn_reqs=( "s" "m" "l" )
syn_pts=( "s" "m" "l" )

#syn_reps=( "1" "2" "3" "4" "5" "6" "7" "8" "9" "10" )

#do only the first matrix for each configuration for now
syn_reps=( "1" )

real_configs=( "DS" "GB" "JD" "LF" "RM" "RP" "SK" "SR" "TM" )
real_types=( "Coverage.dat" "Time.dat" "Seed.dat" "Results.dat" )

#debug:
#echo $user_path
#echo $syn_data_path
#echo $real_data_path
#echo $config_path
#echo $output_path
#echo $syn_output_path
#echo $real_output_path
#echo ${syn_types[0]} ${syn_types[1]} ${syn_types[2]} 

#data_formats=( "0" "1" )

#do only real configs for now
data_formats=( "1" )

mut_operators=( "0" "1" "2" "3" "4" "5" )
cross_operators=( "0" "1" "2" "3" "4" "5" "6" )
select_operators=( "0" "1" "3" )
fit_transforms=( "0" "1" "2" )

#mut_rates=( "0" "0.1" "0.2" "0.3" "0.4" "0.5" )
mut_rates=("0.05" "0.1" "0.15")

child_reps=( "0.6" "0.8" "1.0" )

#pop_sizes=( "50" "60" "70" "80" "90" "100" "150" "200" "300" "400" "450" "500" "1000")
pop_sizes=("50" "100" "150")

max_times=( "10000000" )
max_fitnesses=( "1.0" )

#max_stags=( "10" "15" "20" "25" "30" "35" "40" "50" "60" "80" "100" )
#max_stags=("40")
max_stags=( "10" "25" )


metrics=( "0" )
#reps=( "10" )

#1 rep only due to time
reps=( "1" )

for rep in ${reps[*]}
do

for metric in ${metrics[*]}
do

for max_stag in ${max_stags[*]}
do

for max_fitness in ${max_fitnesses[*]}
do

for max_time in ${max_times[*]}
do

for pop_size in ${pop_sizes[*]}
do

for child_rep in ${child_reps[*]}
do

for mut_rate in ${mut_rates[*]}
do

for fit_transform in ${fit_transforms[*]}
do

for select_operator in ${select_operators[*]}
do

for cross_operator in ${cross_operators[*]}
do

for mut_operator in ${mut_operators[*]}
do

for data_format in ${data_formats[*]}
do


if [ $data_format -eq 0 ]
then

for syn_pt in ${syn_pts[*]}
do

for syn_req in ${syn_reqs[*]}
do

for syn_test in ${syn_tests[*]}
do

for syn_bal in ${syn_bals[*]}
do

for syn_rep in ${syn_reps[*]}
do

echo "java gelations.MakeConfiguration $data_format $mut_operator $cross_operator $select_operator $fit_transform $mut_rate $child_rep $pop_size $max_time $max_fitness $max_stag $metric $syn_data_path${syn_types[1]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $syn_data_path${syn_types[0]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $syn_data_path${syn_types[2]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $syn_output_path${syn_types[3]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $rep"

java gelations.MakeConfiguration $data_format $mut_operator $cross_operator $select_operator $fit_transform $mut_rate $child_rep $pop_size $max_time $max_fitness $max_stag $metric $syn_data_path${syn_types[1]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $syn_data_path${syn_types[0]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $syn_data_path${syn_types[2]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $syn_output_path${syn_types[3]}$syn_bal$syn_test$syn_req$syn_pt$syn_rep $rep

done

done

done

done

done

elif [ $data_format -eq 1 ]
then

for real_config in ${real_configs[*]}
do

echo "java gelations.MakeConfiguration $data_format $mut_operator $cross_operator $select_operator $fit_transform $mut_rate $child_rep $pop_size $max_time $max_fitness $max_stag $metric $real_data_path$real_config${real_types[0]} $real_data_path$real_config${real_types[1]} $real_data_path$real_config${real_types[2]} $real_output_path$real_config${real_types[3]} $rep"

java gelations.MakeConfiguration $data_format $mut_operator $cross_operator $select_operator $fit_transform $mut_rate $child_rep $pop_size $max_time $max_fitness $max_stag $metric $real_data_path$real_config${real_types[0]} $real_data_path$real_config${real_types[1]} $real_data_path$real_config${real_types[2]} $real_output_path$real_config${real_types[3]} $rep

done

fi


done

done

done

done

done

done

done

done

done

done

done

done

done



exit 0