#!/bin/bash

for config in $( ls /home/cs2/conrada/Catterwampus/configs/real_*_DM_CX_ROU_UNT_0.1_0.6_50_1.0E7_1.0_40_0_ )
do

echo "java gelations.ResetDatafile $config"
java gelations.ResetDatafile $config

done

exit 0